stages:
  - linting
  - build and test

linting:
  stage: linting
  image: condaforge/mambaforge:22.9.0-2
  script:
    - mamba install autoflake black isort flake8
    - autoflake --remove-all-unused-imports --check-diff --recursive .
    - isort --check-only --profile black .
    - black --check --line-length 120 .
    - flake8 --ignore=E203,E501 --extend-ignore=W503 --max-line-length=120  .

build and test:
  stage: build and test
  image: mambaorg/micromamba:latest
  script:
    - mamba install --file requirements.txt
    - BUILD_WITH_MARMOT=0 pip install .
    - run_tests_edelweissfe testfiles/
